apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t3a.medium
    desiredCapacity: 2
  - name: ng-2
    instanceType: t3a.medium
    desiredCapacity: 2
