version: '3.3'

services:
  gateway:
    image: steadybit/gateway:latest
    ports:
    - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  fashion:
    image: steadybit/bestseller-fashion:latest
    ports:
    - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  toys:
    image: steadybit/bestseller-toys:latest
    ports:
    - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  hot-deals:
    image: steadybit/hot-deals:latest
    ports:
    - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker