spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true

rest:
  endpoint:
    fashion: "http://fashion-bestseller.steadybit-demo.svc.cluster.local:8082/fashion/bestseller"
    toys: "http://toys-bestseller.steadybit-demo.svc.cluster.local:8081/toys/bestseller"
    hotdeals: "http://hot-deals.steadybit-demo.svc.cluster.local:8083/hotdeals"